// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh7K-2WmYu6Z_QYO4JhpoSoaHN7Dual-4',
    appId: '1:942492238948:web:a728ca9517da03e365cb71',
    messagingSenderId: '942492238948',
    projectId: 'produtoapp-70487',
    authDomain: 'produtoapp-70487.firebaseapp.com',
    storageBucket: 'produtoapp-70487.firebasestorage.app',
    measurementId: 'G-3KV9JZ6DJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhI5ccgL-a86yEP5Fyx_tQYgroHe777fU',
    appId: '1:942492238948:android:1b3026de2956b52f65cb71',
    messagingSenderId: '942492238948',
    projectId: 'produtoapp-70487',
    storageBucket: 'produtoapp-70487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlysMfNgJN_t-lYvePXlW1usrMscYSR8Y',
    appId: '1:942492238948:ios:5ed7655d1264170f65cb71',
    messagingSenderId: '942492238948',
    projectId: 'produtoapp-70487',
    storageBucket: 'produtoapp-70487.firebasestorage.app',
    iosBundleId: 'com.example.produtoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlysMfNgJN_t-lYvePXlW1usrMscYSR8Y',
    appId: '1:942492238948:ios:5ed7655d1264170f65cb71',
    messagingSenderId: '942492238948',
    projectId: 'produtoapp-70487',
    storageBucket: 'produtoapp-70487.firebasestorage.app',
    iosBundleId: 'com.example.produtoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh7K-2WmYu6Z_QYO4JhpoSoaHN7Dual-4',
    appId: '1:942492238948:web:33edbc8e4809b9f865cb71',
    messagingSenderId: '942492238948',
    projectId: 'produtoapp-70487',
    authDomain: 'produtoapp-70487.firebaseapp.com',
    storageBucket: 'produtoapp-70487.firebasestorage.app',
    measurementId: 'G-GRY9RZYQ89',
  );

  
}


